@echo off
setlocal

cd /d "%~dp0"

set "IMOU_VERIFIED_VIEWER=opencv"
set "IMOU_FORCE_RELAY=1"
set "IMOU_RTSP_SUBTYPE=0"
set "IMOU_NO_FRAME_RESTART_SEC=10"
set "IMOU_BOOTSTRAP_ATTEMPTS=4"
set "IMOU_FIRST_FRAME_TIMEOUT_SEC=6"
set "IMOU_TUNNEL_RESTART_COOLDOWN_SEC=45"
set "IMOU_RECOVER_BACKOFF_SEC=2.5"
set "IMOU_CAPTURE_OPEN_TIMEOUT_MS=6000"
set "IMOU_CAPTURE_READ_TIMEOUT_MS=6000"
set "IMOU_RTSP_FFMPEG_TIMEOUT_US=2000000"
set "IMOU_RTSP_FFMPEG_RW_TIMEOUT_US=2000000"
set "IMOU_RTSP_FFMPEG_MAX_DELAY_US=500000"

call "%~dp0run_stop_all.bat"
call "%~dp0run_viewer_opencv.bat" 0
